services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      DB_HOST: "mysql-appg1d.alwaysdata.net"
      DB_NAME: "appg1d_groupeb"
      DB_USER: "appg1d_groupeb"
      DB_PASS: "Dev$$G11B"