services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      DB_HOST: "mysql-appg1d.alwaysdata.net"
      DB_NAME: "appg1d_projetcommun"
      DB_USER: "appg1d_groupeb"
      DB_PASS: "Dev$$G11B"
      SMTP_HOST: "mailhog"
      SMTP_PORT: "1025"
      SMTP_USERNAME: ""
      SMTP_PASSWORD: ""
      FROM_EMAIL: "notifications@manegepark.com"
      FROM_NAME: "ManegePark Notifications"
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI

volumes:
  db_data: